name: ci
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ github.ref }}

      - name: Install mkdocs material
        run: pip install mkdocs-material

      - name: Install dependencies with pip
        run: pip install mkdocs-git-revision-date-localized-plugin mkdocs-glightbox "mkdocs-material[imaging]"

      - name: Deploy site to github pages
        run: mkdocs gh-deploy --force
